# Generated by Django 3.2.5 on 2021-07-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_remove_subscribe_c_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='blogger',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='fans',
            field=models.TextField(),
        ),
    ]
