# Generated by Django 3.2.5 on 2021-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210706_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='a_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
